dns/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView, ListView
from dns.models import Domain

urlpatterns = patterns('dns.views',
    url(r'^domain/$', ListView.as_view(
            model=Domain,
            context_object_name="domain_list",
        ),
        name='domain_list'
    ),
    url(r'^domain/(?P<pk>(\w+\.)+\w+)$', DetailView.as_view(
            model=Domain,
            context_object_name="domain",
        ),
        name='domain_detail'
    ),

    url(r'^bind/named.zones.conf$', ListView.as_view(
            model=Domain,
            context_object_name="domain_list",
            template_name="dns/bind/named.zones.conf",
        ),
        name='bind_named.zones.conf'
    ),
    url(r'^bind/(?P<pk>(\w+\.)+\w+).zone$', DetailView.as_view(
            model=Domain,
            context_object_name="domain",
            template_name="dns/bind/template.zone",
        ),
        name='bind_domain.zone'
    ),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^$', 'demo.views.home', name='home'),
    url(r'^dns/', include('dns.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

dns/models.py
from django.db import models

class Handle(models.Model):
    def __unicode__(self):
        return 'HANDLE-%d' % self.pk

class HandleData(models.Model):
    handle = models.ForeignKey(Handle)
    field = models.CharField(max_length=255)
    value = models.CharField(max_length=255)

    class Meta:
        ordering = ['handle', 'field']
        unique_together = ('handle', 'field')

class Domain(models.Model):
    name = models.CharField(max_length=63, primary_key=True)
    ttl = models.PositiveIntegerField(default=14400)

    handles = models.ManyToManyField(Handle, through='DomainHandle')

    @models.permalink
    def get_absolute_url(self):
        return ('domain_detail', [self.pk])

    def __unicode__(self):
        return self.name

class DnsRecord(models.Model):
    RR_TYPES = (
            ('A', 'Host Address'),
            ('NS', 'Name Server'),
            ('CNAME', 'Canonical Name'),
            ('PTR', 'Domain Name Pointer'),
            ('MX', 'Mail Exchange'),
            ('TXT', 'Text'),
            ('SRV', 'Service'),
    )

    domain = models.ForeignKey(Domain)
    name = models.CharField(max_length=63, blank=True)
    type = models.CharField(max_length=5, choices=RR_TYPES)
    ttl = models.PositiveIntegerField(blank=True)
    data = models.CharField(max_length=255)

    def __unicode__(self):
        if self.name:
            return ".".join([self.name, self.domain.name])
        else:
            return self.domain.name

class DomainHandle(models.Model):
    HANDLE_TYPES = (
            ('tech', 'Technical Contact'),
            ('admin', 'Administrative Contact'),
            ('owner', 'Domain Owner'),
    )
    handle = models.ForeignKey(Handle)
    domain = models.ForeignKey(Domain)
    type = models.CharField(max_length=5, choices=HANDLE_TYPES)

    class Meta:
        unique_together = ('domain', 'type')

dns/views.py
# Create your views here.

dns/templates/dns/domain_detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Domains - {{ domain }}{% endblock %}

{% block content %}
<h1>{{ domain }}</h1>
<dl>
	<dt>TTL</dt>
	<dd>{{ domain.ttl }}</dd>
</dl>

<h2>Handles</h2>
{% for domainhandle in domain.domainhandle_set.all %}
<div class="handle">
	<h3>{{ domainhandle.get_type_display }}: {{ domainhandle.handle }}</h3>
	<dl>
		{% for handledata in domainhandle.handle.handledata_set.all %}
		<dt>{{ handledata.field }}</dt>
		<dd>{{ handledata.value }}</dd>
		{% endfor %}
	</dl>
</div>
{% endfor %}

<h2>Records</h2>
<table>
	<tr>
		<th>Name</th>
		<th>Type</th>
		<th>TTL</th>
		<th>Value</th>
	</tr>
	{% for record in domain.dnsrecord_set.all %}
	<tr>
		<td>{{ record }}</td>
		<td><abbr title="{{ record.get_type_display }}">{{ record.type }}</abbr></td>
		<td>{% if record.ttl %}{{ record.ttl }}{% endif %}</td>
		<td>{{ record.data }}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

dns/templates/dns/domain_list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Domains{% endblock %}

{% block content %}
<h1>Domains</h1>
<a href="{% url bind_named.zones.conf %}" id="zones" >BIND zones.conf</a>
<ul>
{% for domain in object_list %}
	<li>
		<a href="{{ domain.get_absolute_url }}">{{ domain }}</a>
		(<a href="{% url bind_domain.zone domain %}" class="zone">{{ domain }}.zone</a>)
	</li>
{% endfor %}
</ul>
{% endblock %}

templates/base.html
<!doctype html>
<html>
	<head>
		<title>
			{% block title %}Demo{% endblock %}
		</title>
	</head>
	<body>
		{% block content %}{% endblock %}
	</body>
</html>